version: '3'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: sales-api
    ports:
      - '3333:3333'
    volumes:
      - .:/home/node/app
    depends_on:
      - db
      - redis

  db:
    build: .docker/postgres
    container_name: salesapi-db
    restart: unless-stopped
    tty: true
    ports:
      - '5432:5432'
    volumes:
      - .docker/dbData:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=apivendas

  redis:
    image: 'bitnami/redis:latest'
    container_name: salesapi-redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes

  pgadmin:
    image: dpage/pgadmin4
    container_name: salesapi-pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@email.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - '8000:80'
    depends_on:
      - db
